title: Skyve User Guide
description: End user guide for applications written using the Skyve framework.
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-include-cache

# Reading Files
include:
  - .htaccess
  - _pages
keep_files:
  - .git
encoding: "utf-8"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"